# Generated by Django 3.2.4 on 2021-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('birth', models.DateField(max_length=8)),
                ('risk', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('vaccinated', 'Vaccinated'), ('infected', 'Infected'), ('uci', 'UCI'), ('recuperated', 'Recuperated')], max_length=15)),
            ],
        ),
    ]
