# Generated by Django 3.2.4 on 2021-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=30)),
                ('poblation', models.CharField(max_length=30)),
            ],
        ),
    ]
